package cn.com.colibri.itsystem.domain;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

/*********************************************************************************************************
 * Copyright (c)
 * All rights reserved.
 *
 * 文件名称:public class MaintainOrder{ } 
 * 
 * 摘    要： maintainOrder
 * 版    本：1.0
 * 作    者：liuxueli
 * 创建于：2019-05-24 05:27:31
 * 最后修改时间：
 * 
 *********************************************************************************************************/
public class MaintainOrder  implements Serializable  {

	/**
     * 意义，目的和功能，以及被用到的地方<br>
     */
    private static final long serialVersionUID = 1L;
    
	/**
	 * 添加一个空的构造函数（为了Jackson做转换）。
	 */
	public MaintainOrder() {
	}
	
	/**ID*/
	private Long id;

	/**工号*/
	private Integer jobNumber;
	/**真实姓名*/
	private String realName;
	/**部门*/
	private String department;
	/**问题描述*/
	private String description;
	/**维修类别*/
	private Integer maintainType;
	/**状态，1、未分配，2、待处理，3、挂起，4、已完成*/
	private Integer status;
	/**备注*/
	private String remak;
	/**创建时间*/
	private java.util.Date createTime;
	/**结束时间*/
	private java.util.Date endTime;
	/**处理人ID*/
	private Long userId;
    
    /**
     * 扩展参数
     */
    private Map<String,Object> extData =new HashMap<String, Object>();
    
    /**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.ID
	 * ID
	 * @return the value of MAINTAIN_ORDER.ID
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.ID
	 * ID
	 * @param id the value for MAINTAIN_ORDER.ID
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.JOB_NUMBER
	 * 工号
	 * @return the value of MAINTAIN_ORDER.JOB_NUMBER
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public Integer getJobNumber() {
		return jobNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.JOB_NUMBER
	 * 工号
	 * @param jobNumber the value for MAINTAIN_ORDER.JOB_NUMBER
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setJobNumber(Integer jobNumber) {
		this.jobNumber = jobNumber;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.REAL_NAME
	 * 真实姓名
	 * @return the value of MAINTAIN_ORDER.REAL_NAME
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.REAL_NAME
	 * 真实姓名
	 * @param realName the value for MAINTAIN_ORDER.REAL_NAME
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setRealName(String realName) {
		this.realName = realName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.DEPARTMENT
	 * 部门
	 * @return the value of MAINTAIN_ORDER.DEPARTMENT
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.DEPARTMENT
	 * 部门
	 * @param department the value for MAINTAIN_ORDER.DEPARTMENT
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setDepartment(String department) {
		this.department = department;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.DESCRIPTION
	 * 问题描述
	 * @return the value of MAINTAIN_ORDER.DESCRIPTION
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.DESCRIPTION
	 * 问题描述
	 * @param description the value for MAINTAIN_ORDER.DESCRIPTION
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setDescription(String description) {
		this.description = description;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.MAINTAIN_TYPE
	 * 维修类别
	 * @return the value of MAINTAIN_ORDER.MAINTAIN_TYPE
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public Integer getMaintainType() {
		return maintainType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.MAINTAIN_TYPE
	 * 维修类别
	 * @param maintainType the value for MAINTAIN_ORDER.MAINTAIN_TYPE
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setMaintainType(Integer maintainType) {
		this.maintainType = maintainType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.STATUS
	 * 状态，1、未分配，2、待处理，3、挂起，4、已完成
	 * @return the value of MAINTAIN_ORDER.STATUS
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.STATUS
	 * 状态，1、未分配，2、待处理，3、挂起，4、已完成
	 * @param status the value for MAINTAIN_ORDER.STATUS
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setStatus(Integer status) {
		this.status = status;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.REMAK
	 * 备注
	 * @return the value of MAINTAIN_ORDER.REMAK
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public String getRemak() {
		return remak;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.REMAK
	 * 备注
	 * @param remak the value for MAINTAIN_ORDER.REMAK
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setRemak(String remak) {
		this.remak = remak;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.CREATE_TIME
	 * 创建时间
	 * @return the value of MAINTAIN_ORDER.CREATE_TIME
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public java.util.Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.CREATE_TIME
	 * 创建时间
	 * @param createTime the value for MAINTAIN_ORDER.CREATE_TIME
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setCreateTime(java.util.Date createTime) {
		this.createTime = createTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.END_TIME
	 * 结束时间
	 * @return the value of MAINTAIN_ORDER.END_TIME
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public java.util.Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.END_TIME
	 * 结束时间
	 * @param endTime the value for MAINTAIN_ORDER.END_TIME
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setEndTime(java.util.Date endTime) {
		this.endTime = endTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column MAINTAIN_ORDER.USER_ID
	 * 处理人ID
	 * @return the value of MAINTAIN_ORDER.USER_ID
	 * @mbggenerated 2019-05-24 05:27:31
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column MAINTAIN_ORDER.USER_ID
	 * 处理人ID
	 * @param userId the value for MAINTAIN_ORDER.USER_ID
	 * @mbggenerated 2019-05-24 05:27:31
	 */
    public void setUserId(Long userId) {
		this.userId = userId;
	}
	
	public Map<String, Object> getExtData() {
		return extData;
	}
    /**
     * 设置扩展参数
     * @param extData
     */
	public void setExtData(Map<String, Object> extData) {
		this.extData = extData;
	}
	/**
	 * 添加扩展参数
	 * @param key
	 * @param value
	 */
	public void put(String key,Object value) {
		this.extData.put(key, value);
	}
	/**
	 * 获取扩展参数
	 * @param key
	 * @return
	 */
	public Object get(String key){
		return this.extData.get(key);
	}

	public MaintainOrder(Integer jobNumber
	, String realName
	, String department
	, String description
	, Integer maintainType
	, Integer status
	, String remak
	, java.util.Date createTime
	, java.util.Date endTime
	, Long userId ) {
		this.jobNumber = jobNumber;
		this.realName = realName;
		this.department = department;
		this.description = description;
		this.maintainType = maintainType;
		this.status = status;
		this.remak = remak;
		this.createTime = createTime;
		this.endTime = endTime;
		this.userId = userId;
	}
	
	@Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MaintainOrder other = (MaintainOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getJobNumber() == null ? other.getJobNumber() == null : this.getJobNumber().equals(other.getJobNumber()))            && (this.getRealName() == null ? other.getRealName() == null : this.getRealName().equals(other.getRealName()))            && (this.getDepartment() == null ? other.getDepartment() == null : this.getDepartment().equals(other.getDepartment()))            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))            && (this.getMaintainType() == null ? other.getMaintainType() == null : this.getMaintainType().equals(other.getMaintainType()))            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))            && (this.getRemak() == null ? other.getRemak() == null : this.getRemak().equals(other.getRemak()))            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getJobNumber() == null) ? 0 : getJobNumber().hashCode());
                result = prime * result + ((getRealName() == null) ? 0 : getRealName().hashCode());
                result = prime * result + ((getDepartment() == null) ? 0 : getDepartment().hashCode());
                result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
                result = prime * result + ((getMaintainType() == null) ? 0 : getMaintainType().hashCode());
                result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
                result = prime * result + ((getRemak() == null) ? 0 : getRemak().hashCode());
                result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
                result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
                result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        ;
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", jobNumber=").append(jobNumber);
                sb.append(", realName=").append(realName);
                sb.append(", department=").append(department);
                sb.append(", description=").append(description);
                sb.append(", maintainType=").append(maintainType);
                sb.append(", status=").append(status);
                sb.append(", remak=").append(remak);
                sb.append(", createTime=").append(createTime);
                sb.append(", endTime=").append(endTime);
                sb.append(", userId=").append(userId);
        ;
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

}