package cn.com.colibri.itsystem.domain;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

/*********************************************************************************************************
 * Copyright (c)
 * All rights reserved.
 *
 * 文件名称:public class User{ } 
 * 
 * 摘    要： 用户表
 * 版    本：1.0
 * 作    者：liuxueli
 * 创建于：2019-05-24 04:23:37
 * 最后修改时间：
 * 
 *********************************************************************************************************/
public class User  implements Serializable  {

	/**
     * 意义，目的和功能，以及被用到的地方<br>
     */
    private static final long serialVersionUID = 1L;
    
	/**
	 * 添加一个空的构造函数（为了Jackson做转换）。
	 */
	public User() {
	}
	
	/**ID*/
	private Integer id;

	/**用户名*/
	private String userName;
	/**密码*/
	private String password;
	/**创建时间*/
	private java.util.Date creatTime;
	/**修改时间*/
	private java.util.Date modifyTime;
	/**是否删除，0代表未删除，1代表已删除*/
	private Integer deleteFlag;
	/**地址 1、石岩，2、帝光，3、宏发，4、中山，5、南山，6、苏州，7、成都，8.、坪山，9、郑州，10、宁德*/
	private Integer address;
    
    /**
     * 扩展参数
     */
    private Map<String,Object> extData =new HashMap<String, Object>();
    
    /**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column USER.ID
	 * ID
	 * @return the value of USER.ID
	 * @mbggenerated 2019-05-24 04:23:37
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column USER.ID
	 * ID
	 * @param id the value for USER.ID
	 * @mbggenerated 2019-05-24 04:23:37
	 */
    public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column USER.USER_NAME
	 * 用户名
	 * @return the value of USER.USER_NAME
	 * @mbggenerated 2019-05-24 04:23:37
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column USER.USER_NAME
	 * 用户名
	 * @param userName the value for USER.USER_NAME
	 * @mbggenerated 2019-05-24 04:23:37
	 */
    public void setUserName(String userName) {
		this.userName = userName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column USER.PASSWORD
	 * 密码
	 * @return the value of USER.PASSWORD
	 * @mbggenerated 2019-05-24 04:23:37
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column USER.PASSWORD
	 * 密码
	 * @param password the value for USER.PASSWORD
	 * @mbggenerated 2019-05-24 04:23:37
	 */
    public void setPassword(String password) {
		this.password = password;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column USER.CREAT_TIME
	 * 创建时间
	 * @return the value of USER.CREAT_TIME
	 * @mbggenerated 2019-05-24 04:23:37
	 */
	public java.util.Date getCreatTime() {
		return creatTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column USER.CREAT_TIME
	 * 创建时间
	 * @param creatTime the value for USER.CREAT_TIME
	 * @mbggenerated 2019-05-24 04:23:37
	 */
    public void setCreatTime(java.util.Date creatTime) {
		this.creatTime = creatTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column USER.MODIFY_TIME
	 * 修改时间
	 * @return the value of USER.MODIFY_TIME
	 * @mbggenerated 2019-05-24 04:23:37
	 */
	public java.util.Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column USER.MODIFY_TIME
	 * 修改时间
	 * @param modifyTime the value for USER.MODIFY_TIME
	 * @mbggenerated 2019-05-24 04:23:37
	 */
    public void setModifyTime(java.util.Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column USER.DELETE_FLAG
	 * 是否删除，0代表未删除，1代表已删除
	 * @return the value of USER.DELETE_FLAG
	 * @mbggenerated 2019-05-24 04:23:37
	 */
	public Integer getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column USER.DELETE_FLAG
	 * 是否删除，0代表未删除，1代表已删除
	 * @param deleteFlag the value for USER.DELETE_FLAG
	 * @mbggenerated 2019-05-24 04:23:37
	 */
    public void setDeleteFlag(Integer deleteFlag) {
		this.deleteFlag = deleteFlag;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column USER.ADDRESS
	 * 地址 1、石岩，2、帝光，3、宏发，4、中山，5、南山，6、苏州，7、成都，8.、坪山，9、郑州，10、宁德
	 * @return the value of USER.ADDRESS
	 * @mbggenerated 2019-05-24 04:23:37
	 */
	public Integer getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column USER.ADDRESS
	 * 地址 1、石岩，2、帝光，3、宏发，4、中山，5、南山，6、苏州，7、成都，8.、坪山，9、郑州，10、宁德
	 * @param address the value for USER.ADDRESS
	 * @mbggenerated 2019-05-24 04:23:37
	 */
    public void setAddress(Integer address) {
		this.address = address;
	}
	
	public Map<String, Object> getExtData() {
		return extData;
	}
    /**
     * 设置扩展参数
     * @param extData
     */
	public void setExtData(Map<String, Object> extData) {
		this.extData = extData;
	}
	/**
	 * 添加扩展参数
	 * @param key
	 * @param value
	 */
	public void put(String key,Object value) {
		this.extData.put(key, value);
	}
	/**
	 * 获取扩展参数
	 * @param key
	 * @return
	 */
	public Object get(String key){
		return this.extData.get(key);
	}

	public User(String userName
	, String password
	, java.util.Date creatTime
	, java.util.Date modifyTime
	, Integer deleteFlag
	, Integer address ) {
		this.userName = userName;
		this.password = password;
		this.creatTime = creatTime;
		this.modifyTime = modifyTime;
		this.deleteFlag = deleteFlag;
		this.address = address;
	}
	
	@Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))            && (this.getCreatTime() == null ? other.getCreatTime() == null : this.getCreatTime().equals(other.getCreatTime()))            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
                result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
                result = prime * result + ((getCreatTime() == null) ? 0 : getCreatTime().hashCode());
                result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
                result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
                result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        ;
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
                sb.append(", password=").append(password);
                sb.append(", creatTime=").append(creatTime);
                sb.append(", modifyTime=").append(modifyTime);
                sb.append(", deleteFlag=").append(deleteFlag);
                sb.append(", address=").append(address);
        ;
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

}